VMS=kvm.kemukins kvm.minimal kvm.vzkemukins vagrant.virtualbox.kemukins vagrant.virtualbox.vzkemukins virtualbox.kemukins virtualbox.vzkemukins vz.kemukins

all:

kvm.kemukins:
	(cd $@ && make)

kvm.minimal:
	(cd $@ && make)

kvm.vzkemukins:
	(cd $@ && make)

vagrant.virtualbox.kemukins:
	(cd $@ && make)

vagrant.virtualbox.vzkemukins:
	(cd $@ && make)

virtualbox.kemukins:
	(cd $@ && make)

virtualbox.vzkemukins:
	(cd $@ && make)

vz.kemukins:
	(cd $@ && make)

.PHONY: $(VMS)
