VMS=kvm.kemumaki kvm.lxckemumaki kvm.minimal kvm.vzkemumaki vagrant.virtualbox.kemumaki vagrant.virtualbox.vzkemumaki virtualbox.kemumaki virtualbox.vzkemumaki vz.kemumaki

all:

kvm.kemumaki:
	(cd $@ && make)

kvm.lxckemumaki:
	(cd $@ && make)

kvm.minimal:
	(cd $@ && make)

kvm.vzkemumaki:
	(cd $@ && make)

vagrant.virtualbox.kemumaki:
	(cd $@ && make)

vagrant.virtualbox.vzkemumaki:
	(cd $@ && make)

virtualbox.kemumaki:
	(cd $@ && make)

virtualbox.vzkemumaki:
	(cd $@ && make)

vz.kemumaki:
	(cd $@ && make)

.PHONY: $(VMS)
